language: php
sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

before_install:
  - |
    if [ "x$COVERAGE" != "xyes" ]; then
      mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || true
    fi

before_script:
  - |
    if [ "x$COVERAGE" == "xyes" ] && [[ ! $(php -m | grep -si xdebug) ]]; then
      echo "xdebug is required for coverage"
      exit 1
    fi

install: travis_retry composer -n update --prefer-dist

script:
  - |
    if [ "x$COVERAGE" == "xyes" ]; then
       vendor/bin/phpunit --coverage-text --coverage-clover coverage.xml tests/
    else
       vendor/bin/phpunit tests/
    fi

after_script:
  - |
    if [ "x$COVERAGE" == "xyes" ]; then
      travis_retry wget -O /tmp/coveralls.phar https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      php /tmp/coveralls.phar --verbose --config tests/.coveralls.yml || true
    fi

jobs:
  allow_failures:
    - php: nightly
    - env: DEPENDENCIES=dev

  exclude:
    - php: 7.2

  include:
    - stage: Test
      env: COVERAGE=yes

    - stage: Test
      env: DEPENDENCIES=lowest
      install: travis_retry composer update -n --prefer-lowest --prefer-dist

    - stage: Test
      env: DEPENDENCIES=dev
      install:
        - composer config minimum-stability dev
        - travis_retry composer update -n --prefer-dist

    - stage: Code Quality
      env: LINT
      script: vendor/bin/parallel-lint -e php,phpt src/ tests/

    - stage: Code Quality
      env: CODING_STANDARD
      script: vendor/bin/phpcs

    - stage: Code Quality
      env: STATIC_ANALYSIS
      script: vendor/bin/phpstan analyse

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
